
### User Registration
POST http://localhost:4000/users/register
Content-Type: application/json

{
  "firstName":"King", "lastName":"Hiholike", "email":"king@gmail.com", "password":"king@123", "confirmPassword":"king@123"
}


### User Login
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email":"king@gmail.com", "password":"king@123"
}



### User Data

GET http://localhost:4000/users/getUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtpbmdAZ21haWwuY29tIiwiaWF0IjoxNzIxMzIzNDQ4LCJleHAiOjE3MjEzMjcwNDh9.yl-ePvQ8rt2LTGoVI_iWd3jvP4G-XaWbALDzY2R0ldk

{
  "email":"king@gmail.com" 
}
### User Logout

### Forgot Password

POST http://localhost:4000/users/forgot-Password
Content-Type: application/json

{
  "email":"kinghiholike@gmail.com"
}

### Reset Password

POST http://localhost:4000/users/reset-password
Content-Type: application/json

{
  "token":"", "newPassword":"king@123", "confirmNewPassword":"king@123"
}